version: '3'
services:
  client:
    image: rsna:client
    build: ./client
    mem_limit: 8g
    cpus: 4.0
    container_name: client
    ports:
      - 8501:8501
    networks:
      - network

  server:
    image: rsna:server
    build: ./server
    container_name: server
    ports:
      - 8000:8000
    networks:
      - network

  segm:
    image: rsna:segm
    build: ./segm_server
    container_name: segm
    ports:
      - 8001:8001
    networks:
      - network

  clf:
    image: rsna:clf
    build: ./clf_server
    container_name: clf
    ports:
      - 8002:8002
    networks:
      - network

networks:
  network:
    driver: bridge
    name: rsna_network
