AWS_SERVER_PUBLIC_KEY=''
AWS_SERVER_SECRET_KEY=''

AWS_BUCKET=''

SERVER_HOST = 'http://server:8000'

AWS_RDS_USERNAME=''
AWS_RDS_PASSWORD=''
AWS_RDS_ENDPOINT=''
AWS_RDS_PORT=''
AWS_RDS_DB_NAME=''

BATCH_SIZE=8
IMG_SIZE=512
NUM_CHANNELS=3
MODEL_PATH='weights/best_model.onnx'
