AWS_SERVER_PUBLIC_KEY=''
AWS_SERVER_SECRET_KEY=''

AWS_BUCKET=''

SERVER_HOST = 'http://server:8000'

AWS_RDS_USERNAME=''
AWS_RDS_PASSWORD=''
AWS_RDS_ENDPOINT=''
AWS_RDS_PORT=''
AWS_RDS_DB_NAME=''

MASK_IMG_SIZE = 512

BATCH_SIZE=1
SEQUENCE_SIZE = 15
IMG_SIZE=224
NUM_CHANNELS=3
MODEL_PATH='weights/best_model.onnx'
